### ISSUE TITLE
Hide __call__ traceback

### ISSUE THREAD

**Issue by lsglick** [saltstack/pytest-helpers-namespace#2]
We would like to use the helpers namespace to centralize some assert helpers for our tests.

However, the `__call__` method of `FuncWrapper` adds an extra, unnecessary layer to the traceback.

What do you think about adding `__tracebackhide__ = True` at the beginning of `__call__()`?

**Comment by s0undt3ch** [comment]
The pull request has been merged. Closing as fixed.
